name: Environment Variables workflow

on:
  push:
    branches:
      - '**'

jobs:
  display_env:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Ceci est une variable d'environnement
    steps:
      - name: Display Environment Variable
        run: echo $MESSAGE
        