name: Secrets workflow

on:
  push:
    branches:
      - '**'

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Secret
        run: echo "La valeur de SUPER_SECRET est ${{ secrets.SUPER_SECRET }}."